# Use uma imagem base do Node.js
FROM node:18-alpine

# Diretório de trabalho no container
WORKDIR /app

# Copiar apenas os arquivos de dependências
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o restante do código
COPY . .

# Expor a porta usada pelo React
EXPOSE 3000

# Comando para iniciar o React
CMD ["npm", "start"]
