# Use uma imagem base do Node.js
FROM node:18-alpine

# Instalar dependências do sistema necessárias (opcional, mas recomendado)
RUN apk add --no-cache bash curl

# Diretório de trabalho no container
WORKDIR /app

# Copiar apenas os arquivos de dependências
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o restante do código do react-admin
COPY . .

# Expor a porta usada pelo React
EXPOSE 3000

# Comando para iniciar o React
CMD ["npm", "start"]
