version: "3.8"

services:
  mysql:
    container_name: m3_mysql-hotel
    build:
      context: ./DB/init-db
      dockerfile: Dockerfile.mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: hotel
    volumes:
      - ./DB/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 10s

  node:
    container_name: m3_node-app
    build:
      context: .
      dockerfile: Dockerfile.node
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: hotel
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      retries: 10
      start_period: 120s
      timeout: 5s
    user: "node"

  react-admin:
    container_name: m3_react-admin
    build:
      context: ./react-admin
      dockerfile: Dockerfile.react
    depends_on:
      node:
        condition: service_healthy
    ports:
      - "3001:80" # Mapeia a porta 80 do container para a porta 8080 na máquina host
    restart: always # Reinicia automaticamente o container em caso de falha

  