FROM node:18

# Use um usuário não-root
USER node

# Crie o diretório da aplicação com permissões apropriadas
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# Copie apenas os arquivos de dependências inicialmente
COPY --chown=node:node package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código-fonte
COPY --chown=node:node . .

# Compile a aplicação (se necessário)
RUN npm run build

# Defina variáveis de ambiente
ENV HOST=0.0.0.0
ENV PORT=3000

# Exponha a porta do contêiner
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "start"]